services:
  selene:
    image: selene:latest
    # To work with projects, you must mount them into /workspace/ in the container:
    # volumes:
      # - ./my-project:/workspace/my-project
      # - /path/to/another/project:/workspace/another-project
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    ports:
      - "127.0.0.1:${SELENE_PORT:-9121}:9121"
      - "127.0.0.1:${SELENE_DASHBOARD_PORT:-24282}:24282"
    environment:
      - SELENE_DOCKER=1
    command:
      - "uv run --directory . selene-mcp-server --transport sse --port 9121 --host 0.0.0.0"
      # Alternatively add further arguments, e.g. a context
      # - "uv run --directory . selene-mcp-server --transport sse --port 9121 --host 0.0.0.0 --context ide"
