# See Selene's documentation for more details on concept of modes:
# docs/02-usage/050_configuration.md#modes
description: Description of the mode (meta-information only)

# define a prompt which will be included in the system prompt when this mode is activated
# (or will be provided in the project activation message if the mode is activated dynamically).
# See:  docs/02-usage/050_configuration.md#prompt-templates
prompt: |
  This prompt will form part of the system prompt/initial instructions for agents started in this context.
  Add as much content as needed.
  Leave it undefined if no prompt is needed, i.e.
     prompt: null

# tools to be excluded in this context.
# Find the list of tools here: docs/01-about/035_tools.md
excluded_tools: []

# included tools that would otherwise be excluded (particularly optional tools that are disabled by default).
# Find the list of tools here: docs/01-about/035_tools.md
included_optional_tools: []

# fixed set of tools to use as the base tool set (if non-empty), replacing Selene's default set of tools.
# This cannot be combined with non-empty excluded_tools or included_optional_tools.
# Find the list of tools here: docs/01-about/035_tools.md
fixed_tools: []
