const {chromium}=require(process.argv[2]);
const fs=require('fs');
(async()=>{
 const port=fs.readFileSync('/tmp/selene-dashboard-port','utf8');
 const browser=await chromium.launch({executablePath:process.argv[3],headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1050}});
 const page=await context.newPage();
 const requests=[],external=[],errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text());});
 await context.route('**/*',route=>{const url=route.request().url();requests.push(url);if(new URL(url).origin!==`http://127.0.0.1:${port}`){external.push(url);return route.abort();}return route.continue();});
 await page.goto(`http://127.0.0.1:${port}/dashboard/`,{waitUntil:'networkidle'});
 await page.locator('[data-page="logs"]').click();
 await page.locator('[data-page="overview"]').click();
 await page.locator('#menu-toggle').click();
 await page.locator('[data-page="stats"]').click();
 await page.waitForFunction(()=>Chart.getChart('count-chart')?.data.labels.length===3);
 await page.waitForTimeout(1200);
 await page.screenshot({path:'security/dashboard-verification.png',fullPage:true});
 const result={title:await page.title(),charts:await page.evaluate(()=>Object.keys(Chart.instances).length),requests:requests.map(u=>new URL(u).pathname),external_requests:external,errors};
 fs.writeFileSync('security/browser-verification.json',JSON.stringify(result,null,2)+'\n');
 console.log(JSON.stringify(result));await browser.close();
 if(external.length||errors.length)process.exit(1);
})().catch(e=>{console.error(e);process.exit(1)});
