###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
add_module_names = False
author = 'Selene contributors'
autoclass_content = 'both'
autodoc_default_options = {'show-inheritance': True}
autodoc_member_order = 'bysource'
autodoc_show_sourcelink = False
autodoc_typehints_format = 'short'
comments_config = {'hypothesis': False, 'utterances': False}
copyright = '2025 by Selene contributors'
exclude_patterns = ['**.ipynb_checkpoints', '.DS_Store', '.jupyter_cache', '.pytest_cache', 'Thumbs.db', '_build', 'docs/autogen_docs.py', 'docs/create_toc.py', 'jupyter_execute']
extensions = ['sphinx_togglebutton', 'sphinx_copybutton', 'myst_nb', 'jupyter_book', 'sphinx_thebe', 'sphinx_comments', 'sphinx_external_toc', 'sphinx.ext.intersphinx', 'sphinx_design', 'sphinx_book_theme', 'sphinx.ext.autodoc', 'sphinx.ext.viewcode', 'sphinx_jupyterbook_latex', 'sphinx_multitoc_numbering']
external_toc_exclude_missing = True
external_toc_path = '_toc.yml'
github_repository = 'selene'
github_username = ''
html_baseurl = ''
html_favicon = '../src/selene/resources/dashboard/selene-icon-32.png'
html_js_files = ['vendor/tex-svg-full.js']
html_logo = ''
html_sourcelink_suffix = ''
html_static_path = ['_static']
html_theme = 'sphinx_book_theme'
html_theme_options = {'logo': {'image_light': '../resources/selene-logo.svg', 'image_dark': '../resources/selene-logo-dark-mode.svg'}}
html_title = 'Selene Documentation'
latex_engine = 'pdflatex'
master_doc = '01-about/000_evaluation-results.md'
mathjax3_config = {'loader': {'load': ['[tex]/configmacros']}, 'tex': {'packages': {'[+]': ['configmacros']}, 'macros': {'vect': ['{\\mathbf{\\boldsymbol{#1}} }', 1], 'E': '{\\mathbb{E}}', 'P': '{\\mathbb{P}}', 'R': '{\\mathbb{R}}', 'abs': ['{\\left| #1 \\right|}', 1], 'simpl': ['{\\Delta^{#1} }', 1], 'amax': '{\\text{argmax}}'}}}
mathjax_path = 'vendor/tex-svg-full.js'
myst_enable_extensions = ['amsmath', 'colon_fence', 'dollarmath', 'linkify', 'substitution', 'tasklist', 'html_admonition', 'html_image']
myst_url_schemes = ['mailto', 'http', 'https']
nb_execution_allow_errors = True
nb_execution_cache_path = ''
nb_execution_excludepatterns = []
nb_execution_in_temp = False
nb_execution_mode = 'off'
nb_execution_timeout = 1000
nb_merge_streams = True
nb_mime_priority_overrides = [['html', 'application/vnd.jupyter.widget-view+json', 10], ['html', 'application/javascript', 20], ['html', 'text/html', 30], ['html', 'text/latex', 40], ['html', 'image/svg+xml', 50], ['html', 'image/png', 60], ['html', 'image/jpeg', 70], ['html', 'text/markdown', 80], ['html', 'text/plain', 90], ['spelling', 'application/vnd.jupyter.widget-view+json', 10], ['spelling', 'application/javascript', 20], ['spelling', 'text/html', 30], ['spelling', 'text/latex', 40], ['spelling', 'image/svg+xml', 50], ['spelling', 'image/png', 60], ['spelling', 'image/jpeg', 70], ['spelling', 'text/markdown', 80], ['spelling', 'text/plain', 90]]
nb_output_stderr = 'show'
numfig = True
pygments_style = 'sphinx'
python_use_unqualified_type_names = True
suppress_warnings = ['myst.domains']
use_jupyterbook_latex = True
use_multitoc_numbering = True
